//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace GCheckout.AutoGen {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("hello", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class Hello {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("bye", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class Bye {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("demo-failure", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class DemoFailure {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("checkout-shopping-cart", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class CheckoutShoppingCart {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("checkout-flow-support")]
        public CheckoutShoppingCartCheckoutflowsupport checkoutflowsupport;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shopping-cart")]
        public ShoppingCart shoppingcart;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class CheckoutShoppingCartCheckoutflowsupport {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-checkout-flow-support")]
        public MerchantCheckoutFlowSupport Item;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class MerchantCheckoutFlowSupport {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("continue-shopping-url", DataType="anyURI")]
        public string continueshoppingurl;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("edit-cart-url", DataType="anyURI")]
        public string editcarturl;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-calculations")]
        public MerchantCalculations merchantcalculations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("request-buyer-phone-number")]
        public bool requestbuyerphonenumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestbuyerphonenumberSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-methods")]
        public MerchantCheckoutFlowSupportShippingmethods shippingmethods;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tax-tables")]
        public TaxTables taxtables;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class MerchantCalculations {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accept-gift-certificates")]
        public bool acceptgiftcertificates;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acceptgiftcertificatesSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accept-merchant-coupons")]
        public bool acceptmerchantcoupons;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acceptmerchantcouponsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-calculations-url", DataType="anyURI")]
        public string merchantcalculationsurl;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class MerchantCheckoutFlowSupportShippingmethods {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flat-rate-shipping", typeof(FlatRateShipping))]
        [System.Xml.Serialization.XmlElementAttribute("pickup", typeof(Pickup))]
        [System.Xml.Serialization.XmlElementAttribute("merchant-calculated-shipping", typeof(MerchantCalculatedShipping))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class FlatRateShipping {
        
        /// <remarks/>
        public Money price;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-restrictions")]
        public ShippingRestrictions shippingrestrictions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Money {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string currency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Decimal Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class ShippingRestrictions {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allowed-areas")]
        public ShippingRestrictionsAllowedareas allowedareas;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("excluded-areas")]
        public ShippingRestrictionsExcludedareas excludedareas;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class ShippingRestrictionsAllowedareas {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("us-state-area", typeof(USStateArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-zip-area", typeof(USZipArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-country-area", typeof(USCountryArea))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class USStateArea {
        
        /// <remarks/>
        public string state;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class USZipArea {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-pattern")]
        public string zippattern;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class USCountryArea {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("country-area")]
        public USAreas countryarea;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public enum USAreas {
        
        /// <remarks/>
        CONTINENTAL_48,
        
        /// <remarks/>
        FULL_50_STATES,
        
        /// <remarks/>
        ALL,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class ShippingRestrictionsExcludedareas {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("us-state-area", typeof(USStateArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-zip-area", typeof(USZipArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-country-area", typeof(USCountryArea))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Pickup {
        
        /// <remarks/>
        public Money price;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class MerchantCalculatedShipping {
        
        /// <remarks/>
        public Money price;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-restrictions")]
        public ShippingRestrictions shippingrestrictions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class TaxTables {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("alternate-tax-tables")]
        [System.Xml.Serialization.XmlArrayItemAttribute("alternate-tax-table", IsNullable=false)]
        public AlternateTaxTable[] alternatetaxtables;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("default-tax-table")]
        public DefaultTaxTable defaulttaxtable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("merchant-calculated")]
        public bool merchantcalculated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool merchantcalculatedSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class AlternateTaxTable {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("alternate-tax-rules")]
        [System.Xml.Serialization.XmlArrayItemAttribute("alternate-tax-rule", IsNullable=false)]
        public AlternateTaxRule[] alternatetaxrules;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool standalone;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool standaloneSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class AlternateTaxRule {
        
        /// <remarks/>
        public System.Double rate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tax-area")]
        public AlternateTaxRuleTaxarea taxarea;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class AlternateTaxRuleTaxarea {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("us-state-area", typeof(USStateArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-zip-area", typeof(USZipArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-country-area", typeof(USCountryArea))]
        public object Item;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class DefaultTaxTable {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("tax-rules")]
        [System.Xml.Serialization.XmlArrayItemAttribute("default-tax-rule", IsNullable=false)]
        public DefaultTaxRule[] taxrules;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class DefaultTaxRule {
        
        /// <remarks/>
        public System.Double rate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-taxed")]
        public bool shippingtaxed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shippingtaxedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tax-area")]
        public DefaultTaxRuleTaxarea taxarea;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class DefaultTaxRuleTaxarea {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("us-state-area", typeof(USStateArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-zip-area", typeof(USZipArea))]
        [System.Xml.Serialization.XmlElementAttribute("us-country-area", typeof(USCountryArea))]
        public object Item;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class ShoppingCart {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cart-expiration")]
        public CartExpiration cartexpiration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Item[] items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-private-data")]
        public System.Xml.XmlElement merchantprivatedata;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class CartExpiration {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("good-until-date")]
        public System.DateTime gooduntildate;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item-description")]
        public string itemdescription;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item-name")]
        public string itemname;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-private-item-data")]
        public System.Xml.XmlElement merchantprivateitemdata;
        
        /// <remarks/>
        public int quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tax-table-selector")]
        public string taxtableselector;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit-price")]
        public Money unitprice;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("checkout-redirect", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class CheckoutRedirect {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("redirect-url")]
        public string redirecturl;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("charge-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class ChargeOrderRequest {
        
        /// <remarks/>
        public Money amount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("refund-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class RefundOrderRequest {
        
        /// <remarks/>
        public Money amount;
        
        /// <remarks/>
        public string comment;
        
        /// <remarks/>
        public string reason;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("cancel-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class CancelOrderRequest {
        
        /// <remarks/>
        public string comment;
        
        /// <remarks/>
        public string reason;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("process-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class ProcessOrderRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("deliver-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class DeliverOrderRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("send-email")]
        public bool sendemail;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendemailSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracking-data")]
        public TrackingData trackingdata;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class TrackingData {
        
        /// <remarks/>
        public string carrier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracking-number")]
        public string trackingnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("add-tracking-data", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class AddTrackingDataRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracking-data")]
        public TrackingData trackingdata;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("send-buyer-message", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class SendBuyerMessageRequest {
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("send-email")]
        public bool sendemail;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendemailSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("archive-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class ArchiveOrderRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("unarchive-order", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class UnarchiveOrderRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("add-merchant-order-number", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class AddMerchantOrderNumberRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-order-number")]
        public string merchantordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("request-received", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class RequestReceivedResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("new-order-notification", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class NewOrderNotification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-billing-address")]
        public Address buyerbillingaddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-id")]
        public long buyerid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-marketing-preferences")]
        public BuyerMarketingPreferences buyermarketingpreferences;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-shipping-address")]
        public Address buyershippingaddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("financial-order-state")]
        public FinancialOrderState financialorderstate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fulfillment-order-state")]
        public FulfillmentOrderState fulfillmentorderstate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-adjustment")]
        public OrderAdjustment orderadjustment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-total")]
        public Money ordertotal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shopping-cart")]
        public ShoppingCart shoppingcart;
        
        /// <remarks/>
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Address {
        
        /// <remarks/>
        public string address1;
        
        /// <remarks/>
        public string address2;
        
        /// <remarks/>
        public string city;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("company-name")]
        public string companyname;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact-name")]
        public string contactname;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("country-code")]
        public string countrycode;
        
        /// <remarks/>
        public string email;
        
        /// <remarks/>
        public string fax;
        
        /// <remarks/>
        public string phone;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postal-code")]
        public string postalcode;
        
        /// <remarks/>
        public string region;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("buyer-marketing-preferences", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class BuyerMarketingPreferences {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-allowed")]
        public bool emailallowed;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public enum FinancialOrderState {
        
        /// <remarks/>
        REVIEWING,
        
        /// <remarks/>
        CHARGEABLE,
        
        /// <remarks/>
        CHARGING,
        
        /// <remarks/>
        CHARGED,
        
        /// <remarks/>
        PAYMENT_DECLINED,
        
        /// <remarks/>
        CANCELLED_BY_GOOGLE,
        
        /// <remarks/>
        CANCELLED,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public enum FulfillmentOrderState {
        
        /// <remarks/>
        NEW,
        
        /// <remarks/>
        PROCESSING,
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        WILL_NOT_DELIVER,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class OrderAdjustment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adjustment-total")]
        public Money adjustmenttotal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-calculation-successful")]
        public bool merchantcalculationsuccessful;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool merchantcalculationsuccessfulSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-codes")]
        public OrderAdjustmentMerchantcodes merchantcodes;
        
        /// <remarks/>
        public OrderAdjustmentShipping shipping;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-tax")]
        public Money totaltax;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class OrderAdjustmentMerchantcodes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coupon-adjustment", typeof(CouponAdjustment))]
        [System.Xml.Serialization.XmlElementAttribute("gift-certificate-adjustment", typeof(GiftCertificateAdjustment))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class CouponAdjustment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applied-amount")]
        public Money appliedamount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calculated-amount")]
        public Money calculatedamount;
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class GiftCertificateAdjustment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applied-amount")]
        public Money appliedamount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calculated-amount")]
        public Money calculatedamount;
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class OrderAdjustmentShipping {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-calculated-shipping-adjustment", typeof(MerchantCalculatedShippingAdjustment))]
        [System.Xml.Serialization.XmlElementAttribute("flat-rate-shipping-adjustment", typeof(FlatRateShippingAdjustment))]
        [System.Xml.Serialization.XmlElementAttribute("pickup-shipping-adjustment", typeof(PickupShippingAdjustment))]
        public object Item;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class MerchantCalculatedShippingAdjustment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-cost")]
        public Money shippingcost;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-name")]
        public string shippingname;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class FlatRateShippingAdjustment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-cost")]
        public Money shippingcost;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-name")]
        public string shippingname;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class PickupShippingAdjustment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-cost")]
        public Money shippingcost;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-name")]
        public string shippingname;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("order-state-change-notification", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class OrderStateChangeNotification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("new-financial-order-state")]
        public FinancialOrderState newfinancialorderstate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("new-fulfillment-order-state")]
        public FulfillmentOrderState newfulfillmentorderstate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("previous-financial-order-state")]
        public FinancialOrderState previousfinancialorderstate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("previous-fulfillment-order-state")]
        public FulfillmentOrderState previousfulfillmentorderstate;
        
        /// <remarks/>
        public string reason;
        
        /// <remarks/>
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("charge-amount-notification", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class ChargeAmountNotification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("latest-charge-amount")]
        public Money latestchargeamount;
        
        /// <remarks/>
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-charge-amount")]
        public Money totalchargeamount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("chargeback-amount-notification", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class ChargebackAmountNotification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("latest-chargeback-amount")]
        public Money latestchargebackamount;
        
        /// <remarks/>
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-chargeback-amount")]
        public Money totalchargebackamount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("refund-amount-notification", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class RefundAmountNotification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("latest-refund-amount")]
        public Money latestrefundamount;
        
        /// <remarks/>
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-refund-amount")]
        public Money totalrefundamount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("risk-information-notification", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class RiskInformationNotification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("google-order-number", DataType="token")]
        public string googleordernumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("risk-information")]
        public RiskInformation riskinformation;
        
        /// <remarks/>
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class RiskInformation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avs-response")]
        public string avsresponse;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("billing-address")]
        public Address billingaddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-account-age")]
        public int buyeraccountage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cvn-response")]
        public string cvnresponse;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eligible-for-protection")]
        public bool eligibleforprotection;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ip-address")]
        public string ipaddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partial-cc-number")]
        public string partialccnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("notification-acknowledgment", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class NotificationAcknowledgment {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("merchant-calculation-callback", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class MerchantCalculationCallback {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-id")]
        public long buyerid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyeridSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("buyer-language")]
        public string buyerlanguage;
        
        /// <remarks/>
        public Calculate calculate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shopping-cart")]
        public ShoppingCart shoppingcart;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Calculate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("anonymous-address", IsNullable=false)]
        public AnonymousAddress[] addresses;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("merchant-code-strings")]
        [System.Xml.Serialization.XmlArrayItemAttribute("merchant-code-string", IsNullable=false)]
        public MerchantCodeString[] merchantcodestrings;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("method", IsNullable=false)]
        public Method[] shipping;
        
        /// <remarks/>
        public bool tax;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class AnonymousAddress {
        
        /// <remarks/>
        public string city;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("country-code")]
        public string countrycode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postal-code")]
        public string postalcode;
        
        /// <remarks/>
        public string region;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class MerchantCodeString {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Method {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("merchant-calculation-results", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class MerchantCalculationResults {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public Result[] results;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class Result {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchant-code-results")]
        public ResultMerchantcoderesults merchantcoderesults;
        
        /// <remarks/>
        public bool shippable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shippableSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipping-rate")]
        public Money shippingrate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("total-tax")]
        public Money totaltax;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("address-id")]
        public string addressid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("shipping-name")]
        public string shippingname;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class ResultMerchantcoderesults {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gift-certificate-result", typeof(GiftCertificateResult))]
        [System.Xml.Serialization.XmlElementAttribute("coupon-result", typeof(CouponResult))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class GiftCertificateResult {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calculated-amount")]
        public Money calculatedamount;
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public bool valid;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    public class CouponResult {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calculated-amount")]
        public Money calculatedamount;
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public bool valid;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("error", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class ErrorResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-message")]
        public string errormessage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("warning-messages")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] warningmessages;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkout.google.com/schema/2")]
    [System.Xml.Serialization.XmlRootAttribute("diagnosis", Namespace="http://checkout.google.com/schema/2", IsNullable=false)]
    public class DiagnoseResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("input-xml")]
        public System.Xml.XmlElement inputxml;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] warnings;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("serial-number")]
        public string serialnumber;
    }
}
