
namespace MerchantTribe.Shipping.FedEx
{

    public enum ServiceType
    {
        PRIORITYOVERNIGHT = 1,
        STANDARDOVERNIGHT = 2,
        FIRSTOVERNIGHT = 3,
        FEDEX2DAY = 4,
        FEDEXEXPRESSSAVER = 5,
        INTERNATIONALPRIORITY = 6,
        INTERNATIONALECONOMY = 7,
        INTERNATIONALFIRST = 8,
        FEDEX1DAYFREIGHT = 9,
        FEDEX2DAYFREIGHT = 10,
        FEDEX3DAYFREIGHT = 11,
        FEDEXGROUND = 12,
        GROUNDHOMEDELIVERY = 13,
        INTERNATIONALPRIORITYFREIGHT = 14,
        INTERNATIONALECONOMYFREIGHT = 15,
        EUROPEFIRSTINTERNATIONALPRIORITY = 16
    }

}